language: c
compiler:
  - clang
  - gcc
  - gcc-5
  - gcc-4.8
  - gcc-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - gcc-4.9
      - gcc-5
      - valgrind
script:
  - mkdir build && cd build
  - cmake ..
  - make VERBOSE=1
  - ctest -V
before_install:
  - sh travis-build.sh
install:
  - make --directory=cmocka-1.1.0/build && make install --directory=cmocka-1.1.0/build
