language: c
compiler:
  - clang
  - gcc
  - gcc-5
  - gcc-4.8
  - gcc-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - gcc-4.9
      - gcc-5
      - valgrind
script:
  - wget https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar -xvf cmocka-1.1.0.tar.xz
  - cd cmocka-1.1.0
  - mkdir build && cd build
  - cmake .. && make && sudo make install
  - cd ../..
  - mkdir build && cd build
  - cmake ..
  - make VERBOSE=1
  - ctest -V
