language: c
compiler:
  - clang
  - gcc-6
  - gcc-5
  - gcc-4.8
  - gcc-4.9
cache:
  directories:
    - cmocka-1.1.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - gcc-4.9
      - gcc-5
      - gcc-6
      - valgrind
script:
  - mkdir debug && cd debug
  - cmake -DTRAVIS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make VERBOSE=1
  - ctest -V
  - cd .. && mkdir release && cd release
  - cmake -DTRAVIS=ON -DCMAKE_BUILD_TYPE=Release ..
  - make VERBOSE=1
  - ctest -V
before_install:
  - sh travis-build.sh
install:
  - make --directory=cmocka-1.1.0/build && make install --directory=cmocka-1.1.0/build
